on:
  push:
    branches:
     - testing
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run dev
